version: '3.8'

services:
  recicla-coleta:
    image: recicla-coleta:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  default:
    driver: bridge

